---
- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat shell=/bin/false home=/usr/share/tomcat createhome=yes
  become: True
  become_method: sudo

- name: Install Tomcat
  become: yes
  unarchive:
    src: "http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.0/bin/apache-tomcat-8.5.0.tar.gz"
    dest: "/usr/share/tomcat"
    owner: "tomcat"
    group: "tomcat"
    remote_src: "true"
    extra_opts: "--strip-components=1"

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Enable App and Host Manager incoming connections
  copy: src=context.xml dest=/usr/share/tomcat/webapps/manager/META-INF/context.xml
  with_items:
    - manager
    - host-manager

- name: Install Tomcat init script
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service

- name: Start Tomcat service
  systemd: state=started enabled=True daemon_reload=yes name=tomcat

- name: insert firewalld rule for tomcat http port
  firewalld: port={{ http_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: insert firewalld rule for tomcat https port
  firewalld: port={{ https_port }}/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: wait for tomcat to start
  wait_for: port={{http_port}}
